### ISSUE TITLE
"Local file `playbooks/roles/base/.gitlab-ci.yml` does not have project!"

### ISSUE THREAD

**Issue by ay-b** [GabLeRoux/docker-gitlab-ci-lint#8]
Hey. 
Got an error and failed to google out what Gitlab means by that. Do you know the reason for it?

My main .gitlab-ci.yml:
```
stages:
  - test
  - deploy

# Here goes includes from roles

include:
  - local: 'playbooks/roles/base/.gitlab-ci.yml'
  - local: 'playbooks/roles/uninstall/.gitlab-ci.yml'
  - local: 'playbooks/roles/update/.gitlab-ci.yml'
  - local: 'playbooks/roles/users/.gitlab-ci.yml'

# Test hosts file upon update
test hosts:
  stage: test
  image: sdesbure/yamllint
  script:
    - yamllint inventories/hosts
  only:
    changes:
      - inventories/*

test yamls:
  stage: test
  image: sdesbure/yamllint
  script:
    - FILES=$(find playbooks -type f | grep yml)
    - for file in $FILES; do yamllint -d "$YAMLLINT" "$file"; done
  only:
    changes:
      - playbooks/*.{yml,yaml}
```
As you see, it includes several other .yml's because I'm going to place such .yml in every role and include it into the main one to avoid having huge unmaintainable ci-file. 
But looks like linter doesn't like includes. 

Is there any way to fix this and have an option to lint ci-files with includes before committing them to the repo?
